name: Update Data from ts_arc_growth_bot

on:
  schedule:
    - cron: "0 0 * * *"    # Runs at midnight UTC (adjust timing as needed)
  workflow_dispatch:  # Allows manual execution

jobs:
  update-data:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the arc_evidence repository (the repository we're updating)
      - name: Checkout arc_evidence repository
        uses: actions/checkout@v3

      # Step 2: Add ts_arc_growth_bot repository as a remote
      - name: Add ts_arc_growth_bot repository
        run: |
          git remote add ts_arc_growth_bot https://github.com/rangeroper/ts_arc_growth_bot.git  # URL of the ts_arc_growth_bot repo
          git fetch ts_arc_growth_bot  # Fetch the latest changes from ts_arc_growth_bot

      # Step 3: Fetch and Checkout the 'master' branch of ts_arc_growth_bot repository
      - name: Fetch and Checkout master branch of ts_arc_growth_bot
        run: |
          git fetch ts_arc_growth_bot master  # Fetch the 'master' branch from the ts_arc_growth_bot repository
          git checkout FETCH_HEAD  # Checkout the fetched 'master' branch from ts_arc_growth_bot

      # Step 4: Debug step - List the files in ts_arc_growth_bot/data/csv to confirm it's there
      - name: List files in ts_arc_growth_bot/data/csv
        run: |
          ls -la ts_arc_growth_bot/data/csv/

      # Step 5: Ensure the 'data/csv' directory exists in arc_evidence repository
      - name: Ensure the 'data/csv' directory exists in arc_evidence repository
        run: |
          mkdir -p data/csv

      # Step 6: Copy CSV files from ts_arc_growth_bot repository to arc_evidence repository
      - name: Copy CSV files from ts_arc_growth_bot to arc_evidence
        run: |
          # Copy CSV files from the ts_arc_growth_bot repo to arc_evidence repo
          cp -r ts_arc_growth_bot/data/csv/* ./data/csv/  # Adjusted to use a relative path

      # Step 7: Debug step - List files in the arc_evidence/data/csv after copy
      - name: List files in arc_evidence/data/csv
        run: |
          ls -la data/csv/

      # Step 8: Commit and Push Data Changes to arc_evidence Repository
      - name: Commit and Push Data Changes to arc_evidence
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add data/csv/*  # Add updated CSV files
          git commit -m "Update CSV metrics data from ts_arc_growth_bot" || echo "No changes to commit"
          git push origin main  # Push to the main branch of the arc_evidence repo
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Allows push access to arc_evidence repository
