name: Update Data from ts_arc_growth_bot

on:
  schedule:
    - cron: "0 0 * * *"    # Runs at midnight UTC (adjust timing as needed)
  workflow_dispatch:  # Allows manual execution

jobs:
  update-data:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the arc_evidence repository (the repository we're updating)
      - name: Checkout arc_evidence repository
        uses: actions/checkout@v3

      # Step 2: Add ts_arc_growth_bot repository as a remote
      - name: Add ts_arc_growth_bot repository
        run: |
          git remote add ts_arc_growth_bot https://github.com/rangeroper/ts_arc_growth_bot.git  # URL of the ts_arc_growth_bot repo
          git fetch ts_arc_growth_bot  # Fetch the latest changes from ts_arc_growth_bot

      # Step 3: Checkout master branch of ts_arc_growth_bot repository
      - name: Checkout master branch of ts_arc_growth_bot
        run: |
          git fetch ts_arc_growth_bot master  # Fetch the 'master' branch from ts_arc_growth_bot repository
          git checkout ts_arc_growth_bot/master  # Checkout the 'master' branch from ts_arc_growth_bot repository

      # Step 4: List the entire file structure of the ts_arc_growth_bot repository
      - name: List the entire file structure of ts_arc_growth_bot
        run: |
          echo "Listing the entire file structure of ts_arc_growth_bot"
          git ls-tree -r HEAD  # List all files in the repository recursively

      # Step 5: List files in ts_arc_growth_bot/data/csv directory
      - name: List files in ts_arc_growth_bot/data/csv
        run: |
          echo "Checking the contents of ts_arc_growth_bot/data/csv"
          ls -la ts_arc_growth_bot/data/csv/  # List the files in ts_arc_growth_bot/data/csv

      # Step 6: Ensure the 'data/csv' directory exists in arc_evidence repository
      - name: Ensure the 'data/csv' directory exists in arc_evidence repository
        run: |
          if [ ! -d "data/csv" ]; then
            echo "Directory data/csv does not exist in arc_evidence repository. Creating it now."
            mkdir -p data/csv  # Create the directory in arc_evidence repo if it doesn't exist
          else
            echo "Directory data/csv already exists in arc_evidence repository."
          fi

      # Step 7: Copy CSV files from ts_arc_growth_bot to arc_evidence repository
      - name: Copy CSV files from ts_arc_growth_bot to arc_evidence
        run: |
          cp ts_arc_growth_bot/data/csv/* ./data/csv/  # Copy files directly instead of directories

      # Step 8: Commit and Push Data Changes to arc_evidence Repository
      - name: Commit and Push Data Changes to arc_evidence
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add data/csv/*  # Add updated CSV files
          git commit -m "Update CSV metrics data from ts_arc_growth_bot" || echo "No changes to commit"
          git push origin main  # Push to the main branch of the arc_evidence repo
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Allows push access to arc_evidence repository
